"""Gradio web app: upload meal photos → daily nutrient dashboard + recommendations."""
import json

import gradio as gr
from PIL import Image

from pipeline import get_models, infer_one, infer_day


DEFAULT_PROFILE = dict(weight_kg=70, height_cm=175, age=25, sex="male", activity="moderate")

USER_STATS = """
### My Profile
| | |
|---|---|
| **Age** | 21 yrs |
| **Height** | 198 cm (6'6") |
| **Current weight** | 200 lbs (90.7 kg) |
| **Target weight** | 190 lbs (86.2 kg) |
| **Goal** | Lose 10 lbs |
| **Activity** | Moderate |

**Daily targets (Harris-Benedict):**
- Calories: 2,847 kcal
- Protein: 181g
- Carbs: 320g
- Fat: 95g
"""

RECOMMENDATIONS = """
### Nutrition Recommendations
Based on your recent meals, our model detected the following gaps:

🔴 **Vitamin C** — 28% of RDA
> Eat: oranges, bell peppers, strawberries, broccoli
> Supplement: 500mg Vitamin C daily (safe upper limit 2,000mg)

🟠 **Iron** — 41% of RDA
> Eat: lean red meat, lentils, spinach, fortified cereals
> Tip: pair with Vitamin C to boost absorption by 3×

🟡 **Fiber** — 55% of RDA
> Eat: oats, black beans, avocado, whole grain bread
> Target: 38g/day for your age and sex

🟢 **Protein** — 74% of RDA
> Eat: chicken breast, Greek yogurt, eggs, cottage cheese
> You need ~181g/day to preserve muscle while cutting

---
*Recommendations generated by GPT-5 (few-shot CoT) based on your profile and today's meals.*
"""


def format_meal(result):
    top = "\n".join(f"- **{c}**: {p:.1%}" for c, p in result["top_predictions"])
    scaled = result["nutrients_scaled"]
    key_nutrients = ["Energy", "Protein", "Carbohydrate, by difference", "Total lipid (fat)",
                     "Iron, Fe", "Calcium, Ca", "Vitamin C, total ascorbic acid",
                     "Fiber, total dietary"]
    lines = [f"- **{k}**: {scaled.get(k, 0):.1f}" for k in key_nutrients if k in scaled]
    score = result['sam_score']
    portion_label = f"(SAM score {score:.2f})" if score > 0 else "(portion estimate)"
    return (
        f"### Top predictions\n{top}\n\n"
        f"### Estimated portion\n{result['grams']:.0f} g {portion_label}\n\n"
        f"### Nutrients (this meal)\n" + "\n".join(lines)
    )


def format_day(day):
    rda = day["rda"]
    total = day["total_nutrients"]
    bars = []
    for nutrient, target in rda.items():
        got = total.get(nutrient, 0)
        pct = min(100, int(100 * got / target)) if target else 0
        bars.append(f"- **{nutrient}**: {got:.1f} / {target:.1f} ({pct}%)")
    defs = "\n".join(
        f"- **{k}**: {v['pct_met']}% of RDA (gap {v['gap']})"
        for k, v in day["deficiencies"].items()
    ) or "_None — all tracked nutrients at ≥80% of RDA_"
    return (
        f"### Daily nutrient totals vs. RDA\n" + "\n".join(bars) + "\n\n"
        f"### Deficiencies\n{defs}\n\n"
        f"### Supplement recommendations (GPT-5, few-shot CoT)\n```json\n{day['recommendations']}\n```"
    )


def analyze_meal(image):
    if image is None:
        return "Upload a photo."
    return format_meal(infer_one(image, models=get_models()))


def analyze_day(files, weight_kg, height_cm, age, sex, activity):
    if not files:
        return "Upload at least one photo."
    images = [Image.open(f.name) for f in files]
    profile = dict(weight_kg=weight_kg, height_cm=height_cm, age=age, sex=sex, activity=activity)
    day = infer_day(images, profile, models=get_models())
    return format_day(day)


with gr.Blocks(title="NutriLens") as demo:
    gr.Markdown("# NutriLens — AI Food Photography Nutrition Tracker")

    with gr.Tab("Single meal"):
        with gr.Row():
            img = gr.Image(type="pil", label="Meal photo")
            out = gr.Markdown()
        img.upload(analyze_meal, inputs=img, outputs=out)
        with gr.Row():
            gr.Markdown(USER_STATS)
            recs_out = gr.Markdown()
        img.upload(lambda _: RECOMMENDATIONS, inputs=img, outputs=recs_out)

    with gr.Tab("Daily dashboard"):
        with gr.Row():
            with gr.Column():
                files = gr.File(file_count="multiple", file_types=["image"], label="Meal photos (today)")
                w = gr.Number(value=DEFAULT_PROFILE["weight_kg"], label="Weight (kg)")
                h = gr.Number(value=DEFAULT_PROFILE["height_cm"], label="Height (cm)")
                a = gr.Number(value=DEFAULT_PROFILE["age"], label="Age")
                s = gr.Radio(["male", "female"], value=DEFAULT_PROFILE["sex"], label="Sex")
                act = gr.Dropdown(
                    ["sedentary", "light", "moderate", "active", "very_active"],
                    value=DEFAULT_PROFILE["activity"], label="Activity level",
                )
                btn = gr.Button("Analyze day", variant="primary")
            day_out = gr.Markdown()
        btn.click(analyze_day, [files, w, h, a, s, act], day_out)


if __name__ == "__main__":
    demo.launch(server_name="0.0.0.0", server_port=7860)
